In [1]:
import duckdb
import pandas as pd

# Conectamos (o creamos) la base de datos local
con = duckdb.connect("lakehouse.duckdb")

# Cargamos los CSV crudos tal cual, sin transformar nada
df_customers_raw = pd.read_csv("../data/raw/customers.csv")
df_products_raw = pd.read_csv("../data/raw/products.csv")
df_orders_raw = pd.read_csv("../data/raw/orders.csv")

# Los registramos como tablas RAW en DuckDB
con.execute("CREATE OR REPLACE TABLE raw_customers AS SELECT * FROM df_customers_raw")
con.execute("CREATE OR REPLACE TABLE raw_products AS SELECT * FROM df_products_raw")
con.execute("CREATE OR REPLACE TABLE raw_orders AS SELECT * FROM df_orders_raw")

print("Tablas RAW creadas correctamente.")
con.execute("SHOW TABLES").df()

Tablas RAW creadas correctamente.

            name
0  raw_customers
1     raw_orders
2   raw_products

In [5]:
con.execute("select * from raw_customers").df()

,customer_id,full_name,email,phone,city,age,registration_date,credit_card_last4
0,1.0,MARIA LOPEZ,maria1@gmail.com,+51 928728463,lima,22.0,2023-02-02,2679-9935-2424-7912
1,2.0,ana torres,ana2@gmail.com,None,Trujillo,19.0,04-04-2024,4257-9928-7873-4611
2,3.0,juan perez,juan3@gmail.com,+51 930868105,Trujillo,41.0,2024-01-25,4527-6514-2674-2519
3,4.0,SOFIA MENDOZA,sofia4@gmail.com,None,Trujillo,33.0,03-22-2023,8527-9785-3045-7201
4,5.0,Camila Vargas,camila5@gmail.com,+51 916150444,cusco,150.0,2025-06-06,4733-5741-2307-4814
5,6.0,Luis Garcia,luis6@gmail.com,+51 959684848,AREQUIPA,60.0,09-15-2024,6820-4432-5374-2169
6,7.0,Diego Fernandez,diego7@gmail.com,+51 995899313,Trujillo,19.0,2025-04-21,4598-6313-1916-4752
7,8.0,pedro castillo,None,+51 986125617,AREQUIPA,-5.0,20/10/2024,6155-4483-9179-7482
8,9.0,Luis Garcia,luis9@gmail.com,+51 945264581,cusco,41.0,05-22-2023,8019-7543-6930-4593
9,10.0,MARIA LOPEZ,maria10@gmail.com,+51 931472420,Piura,22.0,02/09/2024,7916-2040-7304-7252
10,11.0,Luis Garcia,luis11@gmail.com,None,cusco,NaN,25/04/2023,2876-9797-5371-6573
11,12.0,Carlos Ramirez,None,+51 945351479,Trujillo,60.0,06-10-2025,9201-3927-9317-2743
12,13.0,Diego Fernandez,diego13@gmail.com,+51 931682744,lima,33.0,2024-05-15,9837-9689-1009-6310
13,14.0,SOFIA MENDOZA,sofia14@gmail.com,+51 986149359,AREQUIPA,-5.0,02-17-2025,2290-2403-8962-2133
14,15.0,Carlos Ramirez,carlos15@gmail.com,+51 980823176,cusco,60.0,31/12/2024,7932-4470-9835-4295
15,16.0,SOFIA MENDOZA,sofia16@gmail.com,+51 943273328,AREQUIPA,60.0,08-25-2024,4681-2049-6539-1344
16,17.0,Camila Vargas,None,+51 917901903,AREQUIPA,19.0,03-14-2023,4750-2104-1514-6413
17,18.0,Luis Garcia,luis18@gmail.com,None,lima,60.0,2023-07-14,8744-4981-8749-7669
18,19.0,pedro castillo,pedro19@gmail.com,+51 917270733,AREQUIPA,150.0,2025-03-30,2612-1993-7596-6559
19,20.0,ana torres,ana20@gmail.com,None,cusco,19.0,2025-06-14,4006-5563-8579-5092
20,21.0,Diego Fernandez,None,+51 911980765,AREQUIPA,35.0,12/05/2024,2528-4872-3724-7658
21,22.0,pedro castillo,pedro22@gmail.com,None,None,22.0,03-09-2024,7396-5345-8454-5673
22,23.0,Diego Fernandez,diego23@gmail.com,+51 917849494,cusco,60.0,02-21-2023,9883-1998-6138-1936
23,24.0,Diego Fernandez,diego24@gmail.com,+51 920752378,Piura,NaN,2024-02-18,4044-2122-2113-4853
24,25.0,ana torres,ana25@gmail.com,+51 966267415,Trujillo,33.0,11-16-2024,9565-6183-5272-4346
25,26.0,ana torres,ana26@gmail.com,+51 950264926,Piura,-5.0,04-14-2024,8491-6180-2188-1152
26,27.0,MARIA LOPEZ,maria27@gmail.com,+51 927778019,cusco,35.0,2023-10-19,6718-2127-5002-7054
27,28.0,Diego Fernandez,diego28@gmail.com,+51 997775215,Trujillo,-5.0,2025-06-18,9666-1128-5905-2697
28,29.0,MARIA LOPEZ,maria29@gmail.com,+51 947816686,Trujillo,35.0,01/06/2024,4450-6617-4335-5325
29,30.0,juan perez,juan30@gmail.com,+51 915917225,cusco,35.0,06-15-2023,1058-6464-3143-5291
30,31.0,Diego Fernandez,diego31@gmail.com,None,AREQUIPA,28.0,08-19-2024,3442-9938-1590-7049
31,32.0,pedro castillo,None,+51 915354599,cusco,41.0,12-29-2023,6862-4441-5088-2684
32,33.0,Camila Vargas,camila33@gmail.com,+51 931810617,cusco,41.0,24/01/2025,3900-7755-1406-3938
33,34.0,ana torres,ana34@gmail.com,+51 961343880,Trujillo,-5.0,16/04/2025,1634-8711-4644-4269
34,35.0,Luis Garcia,luis35@gmail.com,+51 963481198,Piura,19.0,12-26-2023,6378-5564-2137-5573
35,36.0,pedro castillo,pedro36@gmail.com,None,cusco,NaN,04-22-2023,5279-3925-5349-1626
36,37.0,SOFIA MENDOZA,sofia37@gmail.com,+51 925521714,lima,150.0,26/12/2024,7311-4114-5173-1727
37,38.0,Diego Fernandez,diego38@gmail.com,+51 936445607,None,NaN,30/09/2024,6967-8066-2146-6409
38,39.0,MARIA LOPEZ,maria39@gmail.com,+51 953779528,cusco,-5.0,03-06-2024,7592-5844-3085-4143
39,40.0,Carlos Ramirez,carlos40@gmail.com,+51 910054484,Piura,33.0,03-15-2025,5978-5700-4443-8043
40,6.0,Luis Garcia,luis6@gmail.com,+51 959684848,AREQUIPA,60.0,09-15-2024,6820-4432-5374-2169
41,11.0,Luis Garcia,luis11@gmail.com,None,cusco,NaN,25/04/2023,2876-9797-5371-6573
42,NaN,None,None,None,None,NaN,None,None

In [9]:
con.execute("SELECT COUNT(*) FROM raw_customers").df()
con.execute("SELECT COUNT(*) FROM raw_orders").df()
con.execute("SELECT COUNT(*) FROM raw_products").df()

   count_star()
0            21

In [11]:
con.close()

## Resumen - Ingesta de Datos

Se cargaron los 3 archivos CSV (customers, products, orders) usando Pandas,
y se almacenaron como tablas RAW en una base de datos local DuckDB
(`lakehouse.duckdb`), sin aplicar ninguna transformación, preservando
los datos exactamente como llegaron.

Tablas creadas: raw_customers, raw_products, raw_orders.